const $ = (id) => document.getElementById(id);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const waitFor = async (fn, ms, label) => { const end = Date.now() + ms; while (Date.now() < end) { if (fn()) return; await sleep(500); } throw new Error("timeout waiting for " + label); };
await shot();
$("new-scan").click();
await sleep(300);
const files = await Promise.all([0, 1, 2, 3].map(async (i) => new File([await (await fetch(`/testdata/huron_${i}.png`)).blob()], `p${i}.png`, { type: "image/png" })));
const dt = new DataTransfer(); files.forEach((f) => dt.items.add(f));
$("gallery").files = dt.files; $("gallery").dispatchEvent(new Event("change"));
await sleep(500);
await shot();
const t0 = Date.now();
$("recognise").click();
let last = "";
await waitFor(() => { const s = $("status").textContent; if (s !== last) { console.log("STATUS", s.replace(/\n/g, " | ")); last = s; } return !$("practice").hidden; }, 600000, "practice screen");
const secs = (Date.now() - t0) / 1000;
await sleep(300);
await shot();
const radios = [...document.querySelectorAll('#lines input[type="radio"]')];
radios[2].click();
$("play").click();
await sleep(3000);
const pos = $("position").textContent;
$("play").click();
$("view-toggle").click();
await waitFor(() => document.querySelectorAll("#osmd svg").length >= 4, 30000, "osmd render");
await sleep(500);
await shot();
window.result = { secs, labels: [...document.querySelectorAll("#lines .pick span:first-of-type")].map((s) => s.textContent + " " + s.nextElementSibling.textContent), mine: document.querySelector("#lines li.mine .pick span").textContent, pos, svgs: document.querySelectorAll("#osmd svg").length, library: await new Promise((res) => { const q = indexedDB.open("partscanner"); q.onsuccess = () => { const c = q.result.transaction("scores").objectStore("scores").count(); c.onsuccess = () => res(c.result); }; }) };
